steps:
# Build the image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-west1-docker.pkg.dev/imerlos-dev/quickstart-docker-repo/my-web:v1', '.']
# Push the image to Artifact Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-west1-docker.pkg.dev/imerlos-dev/quickstart-docker-repo/my-web:v1']
# Deploy image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'myweb-autodeployment', '--image', 'us-west1-docker.pkg.dev/imerlos-dev/quickstart-docker-repo/my-web:v1', '--region', 'us-west1', --allow-unauthenticated]
images:
- 'us-west1-docker.pkg.dev/imerlos-dev/quickstart-docker-repo/my-web:v1'
options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/imerlos-dev/locations/us-east1/workerPools/my-private-pool'
